spring:
  application:
    name: walletapi


  datasource:
     url: jdbc:postgresql://localhost:5432/digital
     password: Password
     username: postgres
     driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl: none
    show-sql: true

  liquibase:
    enabled: true
    drop-first: false
    default-schema: wallet
    clear-checksums: true
    change-log: classpath:db/changelog/master.yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"



